backend:
  name: github
  repo: Spharror/academiadevideo
  branch: main

media_folder: images
public_folder: images

collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titlu", name: "title", widget: "string" }
      - { label: "Data publicării", name: "date", widget: "datetime" }
      - { label: "Imagine copertă", name: "cover", widget: "image", required: false }
      - { label: "Descriere scurtă", name: "description", widget: "string", required: false }
      - { label: "Conținut", name: "body", widget: "markdown" }
